NTYPE="node";
EQ=1;
VAR=0;

MTYPE="match";
MATCHED="1";
UNMATCHED="0";

CTYPE="constrained";
WELL_CONSTRAINED=0;
UNDER_CONSTRAINED=1;
OVER_CONSTRAINED=-1;

INDEX="index";
ORIGIN="origin";

FLAG="flag";
FLAG_OVER="flag_over";
FLAG_AUG="flag_augment";
FLAG_DIFF='flag_diff';
FLAG_INDEX="'";

COLOR = 'color';
WIDTH = 'width';
POSITION= 'pos';

DEF_NODE_SHAPE = 'o';
DEF_NODE_SIZE = 400;
DEF_NODE_COLOR = '#4672C4';
DEF_BORDER_WIDTH = 1.0;
DEF_BORDER_COLOR = '#C8C8C8';

CONSTRAINED_NODE_COLOR = '#999999';
WELL_CONSTRAINED_COLOR = CONSTRAINED_NODE_COLOR;
UNDER_CONSTRAINED_COLOR = DEF_NODE_COLOR;
OVER_CONSTRAINED_COLOR = DEF_BORDER_COLOR;

DIFFERENTIATED_NODE_COLOR = '#7246C4';
DIFFERENTIATED_NODE_WIDTH = '2.0';

DEF_EDGE_COLOR = '#888888';
DEF_EDGE_WIDTH = 1.0;
MATCHED_EDGE_COLOR = '#666666'
MATCHED_EDGE_WIDTH = 1.5;

DEF_FONT_SIZE = '9';
DEF_FONT_FAMILY = 'Arial';
DEF_FONT_COLOR = '#FFFFFF';
